import type { DashboardData } from "./types";

export const DASHBOARD_MOCK: DashboardData = {
  ingresosMensuales: [
    { mes: "Enero", valor: 1678.0 },
    { mes: "Febrero", valor: 1494.0 },
    { mes: "Marzo", valor: 1754.4 },
    { mes: "Abril", valor: 1650.0 },
    { mes: "Mayo", valor: 2328.0 },
    { mes: "Junio", valor: 1650.0 },
    { mes: "Julio", valor: 1678.0 },
    { mes: "Agosto", valor: 1494.0 },
    { mes: "Septiembre", valor: 1754.4 },
    { mes: "Octubre", valor: 1651.0 },
    { mes: "Noviembre", valor: 2328.0 },
    { mes: "Diciembre", valor: 1650.0 },
  ],
  gastosMensuales: [
    { mes: "Enero", valor: 1688.76 },
    { mes: "Febrero", valor: 1399.51 },
    { mes: "Marzo", valor: 1083.9 },
    { mes: "Abril", valor: 1589.9 },
    { mes: "Mayo", valor: 906.9 },
    { mes: "Junio", valor: 1133.4 },
    { mes: "Julio", valor: 540.0 },
    { mes: "Agosto", valor: 769.0 },
    { mes: "Septiembre", valor: 1344.4 },
    { mes: "Octubre", valor: 1650.0 },
    { mes: "Noviembre", valor: 328.0 },
    { mes: "Diciembre", valor: 2030.0 },
  ],
  goal: {
    id: "emergency-fund",
    title: "Objetivo Actual: Fondo de emergencia",
    objetivo: 5100,
    ahorrado: 4277,
    description: "Para sobrevivir 8 meses sin ingresos",
  },
  gastosPorCategoria: [
    { name: "Vivienda", value: 1200 },
    { name: "Alimentación", value: 800 },
    { name: "Ocio", value: 400 },
    { name: "Transporte", value: 300 },
    { name: "Salud", value: 250 },
    { name: "Educación", value: 220 },
    { name: "Servicios", value: 180 },
  ],
  ingresosPorCategoria: [
    { name: "Nómina", value: 4200 },
    { name: "Intereses", value: 800 },
    { name: "Freelance", value: 900 },
    { name: "Ventas", value: 600 },
    { name: "Otros", value: 200 },
  ],
  distribucionActivos: [
    { name: "PIAS", value: 1500 },
    { name: "Cuenta de valores", value: 1200 },
    { name: "Wallet Crypto", value: 5 },
    { name: "Cuenta remunerada", value: 4277 },
    { name: "Cuenta Cajamar", value: 236 },
    { name: "Cuenta Revolut", value: 450 },
    { name: "Cuenta Trade Republic", value: 280 },
  ],
  movimientos: [
    // Movimientos históricos
    { id: "mov-1", fecha: "2024-01-03", concepto: "Nómina", categoria: "Nómina", tipo: "Ingreso", cantidad: 2100 },
    { id: "mov-2", fecha: "2024-01-05", concepto: "Alquiler", categoria: "Vivienda", tipo: "Gasto", cantidad: -820 },
    { id: "mov-3", fecha: "2024-02-02", concepto: "Supermercado", categoria: "Alimentación", tipo: "Gasto", cantidad: -140 },
    { id: "mov-4", fecha: "2024-02-18", concepto: "Seguro médico", categoria: "Salud", tipo: "Gasto", cantidad: -90 },
    { id: "mov-5", fecha: "2024-03-08", concepto: "Freelance", categoria: "Freelance", tipo: "Ingreso", cantidad: 450 },
    { id: "mov-6", fecha: "2024-03-14", concepto: "Curso online", categoria: "Educación", tipo: "Gasto", cantidad: -60 },
    { id: "mov-7", fecha: "2024-04-04", concepto: "Nómina", categoria: "Nómina", tipo: "Ingreso", cantidad: 2200 },
    { id: "mov-8", fecha: "2024-04-19", concepto: "Restaurante", categoria: "Ocio", tipo: "Gasto", cantidad: -75 },
    { id: "mov-9", fecha: "2024-05-09", concepto: "Intereses", categoria: "Intereses", tipo: "Ingreso", cantidad: 110 },
    { id: "mov-10", fecha: "2024-05-21", concepto: "Gasolina", categoria: "Transporte", tipo: "Gasto", cantidad: -55 },
    { id: "mov-11", fecha: "2024-06-01", concepto: "Nómina", categoria: "Nómina", tipo: "Ingreso", cantidad: 2300 },
    { id: "mov-12", fecha: "2024-06-12", concepto: "Compras", categoria: "Ocio", tipo: "Gasto", cantidad: -120 },
    { id: "mov-13", fecha: "2024-07-03", concepto: "Servicios", categoria: "Servicios", tipo: "Gasto", cantidad: -95 },
    { id: "mov-14", fecha: "2024-07-20", concepto: "Venta de segunda mano", categoria: "Ventas", tipo: "Ingreso", cantidad: 180 },
    { id: "mov-15", fecha: "2024-08-05", concepto: "Supermercado", categoria: "Alimentación", tipo: "Gasto", cantidad: -160 },
    { id: "mov-16", fecha: "2024-09-02", concepto: "Inversión ETF", categoria: "Inversión", tipo: "Inversión", cantidad: -250 },
    { id: "mov-17", fecha: "2024-10-11", concepto: "Nómina", categoria: "Nómina", tipo: "Ingreso", cantidad: 2350 },
    { id: "mov-18", fecha: "2024-11-10", concepto: "Restaurante", categoria: "Ocio", tipo: "Gasto", cantidad: -85 },
    { id: "mov-19", fecha: "2024-12-02", concepto: "Regalo", categoria: "Otros", tipo: "Gasto", cantidad: -70 },
    
    // Movimientos de Enero 2026 (mes actual) - Distribuidos para vista diaria
    { id: "mov-20", fecha: "2026-01-01", concepto: "Nómina", categoria: "Nómina", tipo: "Ingreso", cantidad: 2400 },
    { id: "mov-21", fecha: "2026-01-02", concepto: "Supermercado", categoria: "Alimentación", tipo: "Gasto", cantidad: -85 },
    { id: "mov-22", fecha: "2026-01-03", concepto: "Gasolina", categoria: "Transporte", tipo: "Gasto", cantidad: -45 },
    { id: "mov-23", fecha: "2026-01-04", concepto: "Farmacia", categoria: "Salud", tipo: "Gasto", cantidad: -25 },
    { id: "mov-24", fecha: "2026-01-05", concepto: "Alquiler", categoria: "Vivienda", tipo: "Gasto", cantidad: -850 },
    { id: "mov-25", fecha: "2026-01-06", concepto: "Cena fuera", categoria: "Ocio", tipo: "Gasto", cantidad: -60 },
    { id: "mov-26", fecha: "2026-01-07", concepto: "Supermercado", categoria: "Alimentación", tipo: "Gasto", cantidad: -92 },
    { id: "mov-27", fecha: "2026-01-08", concepto: "Freelance", categoria: "Freelance", tipo: "Ingreso", cantidad: 350 },
    { id: "mov-28", fecha: "2026-01-09", concepto: "Gimnasio", categoria: "Salud", tipo: "Gasto", cantidad: -40 },
    { id: "mov-29", fecha: "2026-01-10", concepto: "Netflix", categoria: "Servicios", tipo: "Gasto", cantidad: -15 },
    { id: "mov-30", fecha: "2026-01-11", concepto: "Uber", categoria: "Transporte", tipo: "Gasto", cantidad: -12 },
    { id: "mov-31", fecha: "2026-01-12", concepto: "Supermercado", categoria: "Alimentación", tipo: "Gasto", cantidad: -78 },
    { id: "mov-32", fecha: "2026-01-13", concepto: "Cafetería", categoria: "Ocio", tipo: "Gasto", cantidad: -8 },
    { id: "mov-33", fecha: "2026-01-14", concepto: "Libro", categoria: "Educación", tipo: "Gasto", cantidad: -25 },
    { id: "mov-34", fecha: "2026-01-15", concepto: "Bonus", categoria: "Nómina", tipo: "Ingreso", cantidad: 500 },
    { id: "mov-35", fecha: "2026-01-16", concepto: "Luz", categoria: "Servicios", tipo: "Gasto", cantidad: -65 },
    { id: "mov-36", fecha: "2026-01-17", concepto: "Supermercado", categoria: "Alimentación", tipo: "Gasto", cantidad: -105 },
    { id: "mov-37", fecha: "2026-01-18", concepto: "Cine", categoria: "Ocio", tipo: "Gasto", cantidad: -18 },
    { id: "mov-38", fecha: "2026-01-19", concepto: "Gasolina", categoria: "Transporte", tipo: "Gasto", cantidad: -50 },
    { id: "mov-39", fecha: "2026-01-20", concepto: "Freelance", categoria: "Freelance", tipo: "Ingreso", cantidad: 280 },
    { id: "mov-40", fecha: "2026-01-21", concepto: "Ropa", categoria: "Otros", tipo: "Gasto", cantidad: -120 },
    { id: "mov-41", fecha: "2026-01-22", concepto: "Supermercado", categoria: "Alimentación", tipo: "Gasto", cantidad: -88 },
  ],
  budgets: [
    { categoryId: "Vivienda", amount: 850, period: "2024-12" },
    { categoryId: "Alimentación", amount: 420, period: "2024-12" },
    { categoryId: "Transporte", amount: 200, period: "2024-12" },
  ],
  goals: [
    {
      id: "goal-1",
      title: "Viaje verano",
      objetivo: 2500,
      ahorrado: 1250,
      description: "Ahorro para vacaciones de verano",
    },
    {
      id: "goal-2",
      title: "Laptop nueva",
      objetivo: 1800,
      ahorrado: 720,
      description: "Renovar equipo de trabajo",
    },
  ],
  notifications: [
    {
      id: "not-1",
      type: "warning",
      message: "El presupuesto de Alimentación está al 78%.",
      read: false,
      date: "2024-12-08",
    },
    {
      id: "not-2",
      type: "success",
      message: "Has alcanzado el 50% del objetivo Viaje verano.",
      read: true,
      date: "2024-12-03",
    },
  ],
  recurringMovements: [
    {
      id: "rec-1",
      fecha: "2024-12-01",
      concepto: "Nómina",
      categoria: "Nómina",
      tipo: "Ingreso",
      cantidad: 2300,
      frequency: "monthly",
      nextDate: "2025-01-01",
    },
  ],
};

